# This file contains values from Cookiecutter

default_context:
  project_name: "paddle-billing-client"
  project_description: "Python wrapper around the new Paddle Billing API"
  organization: "Benjamin Gervan"
  license: "MIT"
  minimal_python_version: 3.7
  github_name: "bgervan"
  email: "bgervan@webstormit.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
