name: website-stalker

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *' # once per day at 1am

permissions:
  contents: write

jobs:
  website-stalker:
    runs-on: ubuntu-latest
    env:
      WEBSITE_STALKER_FROM: ${{ secrets.WEBSITE_STALKER_FROM }}
    steps:
      - uses: EdJoPaTo/website-stalker-github-action@v1

      - uses: actions/checkout@v3

      - name: Check website-stalker config
        run: website-stalker check

      - name: Run website-stalker
        run: website-stalker run --all

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch: paddle-website-stalker
          commit-message: Update API Reference
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          title: 'Update API Reference'
          assignees: bgervan
          reviewers: bgervan
          draft: false

      - if: always()
        run: git push
